[package]
name = "usbip-runner"
version = { workspace = true }
edition = "2021"

[dependencies]
apps = { path = "../../components/apps", features = ["log-all", "trussed-usbip"] }
cfg-if = { version = "1.0.0" }
clap = { version = "3.0.0", features = ["cargo", "derive"] }
clap-num = "1.0.0"
delog = { version = "0.1.6", features = ["std-log"] }
log = { version = "0.4.14", default-features = false }
rand_core = { version = "0.6.4", features = ["getrandom"] }
pretty_env_logger = "0.4.0"
trussed = { version = "0.1" }
trussed-usbip = { git = "https://github.com/trussed-dev/pc-usbip-runner", features = ["ctaphid"], default-features = false }

[features]
alpha = ["apps/alpha"]
provisioner = ["apps/provisioner"]
