[package]
name = "apps"
version = "0.1.0"
edition = "2021"

[dependencies]
apdu-dispatch = "0.1"
ctaphid-dispatch = "0.1"
trussed = "0.1"
trussed-usbip = { git = "https://github.com/trussed-dev/pc-usbip-runner", features = ["ctaphid"], default-features = false, optional = true }
usbd-ctaphid = { path = "../usbd-ctaphid", optional = true }

# apps
admin-app = { git = "https://github.com/solokeys/admin-app", optional = true }
fido-authenticator = { version = "0.1.1", features = ["dispatch"], optional = true }
ndef-app = { path = "../ndef-app", optional = true }
oath-authenticator = { git = "https://github.com/nitrokey/oath-authenticator", rev = "0.3.0", features = ["apdu-dispatch", "ctaphid"], optional = true }
opcard = { git = "https://github.com/Nitrokey/opcard-rs", rev = "v0.2.0", features = ["apdu-dispatch", "delog", "rsa2048", "rsa4096"], optional = true }
provisioner-app = { path = "../provisioner-app", optional = true }

[features]
default = ["admin-app", "fido-authenticator", "ndef-app"]
alpha = ["oath-authenticator", "opcard"]
provisioner = ["provisioner-app"]

log-all = [
    "admin-app?/log-all",
    "fido-authenticator?/log-all",
    "oath-authenticator?/log-all",
    "opcard?/log-all",
    "provisioner-app?/log-all",
]

# Allow resetting FIDO authenticator (and possibly others) even after 10s uptime
no-reset-time-window = ["fido-authenticator?/disable-reset-time-window"]

fido-authenticator = ["dep:fido-authenticator", "usbd-ctaphid"]
